-- =============================================================================
-- NGU Business Real Estate CMS - COMPLETE database setup, in one file.
--
-- Paste this whole file into the Supabase SQL Editor and hit Run. It is the
-- concatenation of, in order:
--   migrations/0001_init.sql    - schema, RLS, public RPCs
--   migrations/0002_brokers.sql - brokers + listing/lead attribution
--   seed.sql                    - 2 brokers + the 22-listing catalogue
--
-- Safe to re-run: the seed uses ON CONFLICT DO NOTHING / NOT EXISTS guards.
-- Generated by tools/build-all-in-one.ps1 - do not hand-edit.
-- =============================================================================

-- ===========================================================================
-- BEGIN 0001_init.sql
-- ===========================================================================

-- ============================================================================
-- Business Brokerage CMS — initial schema
--
-- Single-tenant: ONE brokerage (you). You (and any staff) log in via Supabase
-- Auth and manage everything. The public site is anonymous — visitors browse
-- published listings, submit inquiries, and sign NDAs to unlock confidential
-- documents. All public writes go through SECURITY DEFINER RPCs so the anon
-- client can never read leads, NDAs, or draft listings.
--
-- Security model: the browser talks to Postgres directly through Supabase, so
-- Row Level Security (RLS) is the real boundary. Every table has RLS enabled.
-- The anon/auth client can ONLY do what the policies + RPCs below allow.
-- ============================================================================

create extension if not exists "pgcrypto";

-- Policies reference helper functions defined below; defer body validation so
-- creation order doesn't error.
set check_function_bodies = off;

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
create type listing_status as enum ('draft', 'active', 'under_offer', 'sold', 'withdrawn');
create type lead_type      as enum ('buyer', 'seller', 'inquiry');
create type lead_stage     as enum ('new', 'contacted', 'nda_signed', 'qualified', 'negotiating', 'closed_won', 'closed_lost');
create type app_role       as enum ('admin', 'staff');

-- ---------------------------------------------------------------------------
-- Helper functions (SECURITY DEFINER so policies can call them without
-- recursing into RLS). STABLE; search_path pinned for safety.
-- ---------------------------------------------------------------------------
create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid());
$$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

-- ===========================================================================
-- IDENTITY — every authenticated user with a profile row is brokerage staff.
-- (There is no public self-signup surfaced; you create staff logins yourself.)
-- ===========================================================================
create table public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  role        app_role    not null default 'staff',
  full_name   text,
  email       text,
  created_at  timestamptz not null default now()
);
alter table public.profiles enable row level security;

create policy "profiles: staff read"   on public.profiles for select using (public.is_staff());
create policy "profiles: self update"  on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy "profiles: admin manage" on public.profiles for all
  using (public.is_admin()) with check (public.is_admin());

-- Provision a profile row when a new auth user is created. First-ever user is
-- promoted to admin automatically; everyone after defaults to staff.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_role app_role;
begin
  select case when not exists (select 1 from public.profiles) then 'admin' else 'staff' end into v_role;
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', ''), v_role);
  return new;
end; $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ===========================================================================
-- LISTINGS — businesses for sale
-- ===========================================================================
create table public.listings (
  id                 uuid primary key default gen_random_uuid(),
  slug               text not null unique,               -- public URL: /listing/<slug>
  status             listing_status not null default 'draft',
  is_featured        boolean not null default false,

  -- Headline / classification
  title              text not null,                       -- "Luxury Hair Salon"
  headline           text,                                -- short teaser line
  category           text,                                -- "Beauty / Personal Care"
  city               text,
  state              text,
  county             text,
  location_note      text,                                -- e.g. "Relocatable" / area hidden for confidentiality

  -- Financials (nullable — not every figure is disclosed)
  asking_price       numeric(14,2),
  cash_flow          numeric(14,2),                        -- SDE / owner benefit
  gross_revenue      numeric(14,2),
  ebitda             numeric(14,2),
  ffe                numeric(14,2),                        -- furniture, fixtures & equipment value
  inventory          numeric(14,2),
  real_estate_value  numeric(14,2),
  rent               numeric(14,2),                        -- monthly rent
  is_ffe_included    boolean not null default true,
  is_inventory_included boolean not null default true,
  seller_financing   boolean not null default false,

  -- Narrative / details
  description        text,                                -- long free-text
  reason_for_selling text,
  support_training   text,
  growth_expansion   text,
  competition        text,
  facilities         text,
  established_year   int,
  employees          text,                                -- free text: "8 FT, 3 PT"
  real_estate        text,                                -- "Leased" / "Owned"
  building_sf        text,
  lease_expiration   text,
  is_franchise       boolean not null default false,

  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
alter table public.listings enable row level security;
create trigger listings_touch before update on public.listings for each row execute function public.touch_updated_at();
create index on public.listings (status);
create index on public.listings (category);
create index on public.listings (state, city);

-- A listing is "live" (publicly visible) when active / under_offer / sold.
create or replace function public.listing_is_live(s listing_status)
returns boolean language sql immutable as $$
  select s in ('active', 'under_offer', 'sold');
$$;

create policy "listings: public read live" on public.listings for select
  using (public.listing_is_live(status) or public.is_staff());
create policy "listings: staff write" on public.listings for all
  using (public.is_staff()) with check (public.is_staff());

-- ===========================================================================
-- LISTING IMAGES — public photos shown on the listing
-- ===========================================================================
create table public.listing_images (
  id          uuid primary key default gen_random_uuid(),
  listing_id  uuid not null references public.listings(id) on delete cascade,
  url         text not null,                              -- Supabase Storage public URL or external
  caption     text,
  is_primary  boolean not null default false,
  sort_order  int not null default 0,
  created_at  timestamptz not null default now()
);
alter table public.listing_images enable row level security;
create index on public.listing_images (listing_id, sort_order);

create policy "images: read where listing readable" on public.listing_images for select
  using (exists (
    select 1 from public.listings l
    where l.id = listing_id and (public.listing_is_live(l.status) or public.is_staff())
  ));
create policy "images: staff write" on public.listing_images for all
  using (public.is_staff()) with check (public.is_staff());

-- ===========================================================================
-- DOCUMENTS — confidential material (CIM, financials). NDA-gated.
-- Metadata is staff-only; the public reaches these ONLY through the
-- request_documents() RPC after signing an NDA for that listing.
-- ===========================================================================
create table public.documents (
  id           uuid primary key default gen_random_uuid(),
  listing_id   uuid not null references public.listings(id) on delete cascade,
  name         text not null,                             -- "Confidential Information Memorandum"
  file_url     text not null,                             -- storage URL delivered post-NDA
  requires_nda boolean not null default true,
  is_available boolean not null default true,             -- broker toggle to release/withhold
  sort_order   int not null default 0,
  created_at   timestamptz not null default now()
);
alter table public.documents enable row level security;
create index on public.documents (listing_id, sort_order);

-- Staff only. The public never selects this table directly.
create policy "documents: staff all" on public.documents for all
  using (public.is_staff()) with check (public.is_staff());

-- ===========================================================================
-- LEADS — inquiries, prospective buyers, prospective sellers. NEVER public.
-- ===========================================================================
create table public.leads (
  id          uuid primary key default gen_random_uuid(),
  type        lead_type   not null default 'inquiry',
  stage       lead_stage  not null default 'new',
  listing_id  uuid references public.listings(id) on delete set null, -- inquiry about a listing
  name        text not null,
  email       text,
  phone       text,
  company     text,
  message     text,                                       -- their original message
  -- Buyer qualification / seller intake (free text, filled by broker)
  budget      text,
  timeframe   text,
  notes       text,                                       -- private broker notes
  source      text not null default 'website',            -- website | referral | manual | ...
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
alter table public.leads enable row level security;
create trigger leads_touch before update on public.leads for each row execute function public.touch_updated_at();
create index on public.leads (stage);
create index on public.leads (type);
create index on public.leads (listing_id);
create index on public.leads (created_at desc);

-- Staff only. Public creates leads through submit_inquiry() (security definer).
create policy "leads: staff all" on public.leads for all
  using (public.is_staff()) with check (public.is_staff());

-- ===========================================================================
-- NDAs — signature records. NEVER public. Created via sign_nda() RPC.
-- ===========================================================================
create table public.ndas (
  id                uuid primary key default gen_random_uuid(),
  listing_id        uuid references public.listings(id) on delete set null,
  lead_id           uuid references public.leads(id) on delete set null,
  signer_name       text not null,
  signer_email      text not null,
  signer_phone      text,
  agreement_version text not null default 'v1',
  signed_at         timestamptz not null default now()
);
alter table public.ndas enable row level security;
create index on public.ndas (listing_id);
create index on public.ndas (signer_email);

create policy "ndas: staff read" on public.ndas for select using (public.is_staff());
-- inserts happen via sign_nda() (security definer), not the client.

-- ===========================================================================
-- PUBLIC RPCs — the only way the anonymous site writes data.
-- ===========================================================================

-- Contact / inquiry form on a listing (or general contact). Creates a lead.
create or replace function public.submit_inquiry(
  p_name text,
  p_email text,
  p_message text,
  p_phone text default null,
  p_listing_id uuid default null,
  p_type lead_type default 'inquiry'
) returns void
language plpgsql security definer set search_path = public as $$
begin
  if coalesce(trim(p_name), '') = '' or coalesce(trim(p_email), '') = '' then
    raise exception 'Name and email are required';
  end if;
  -- If a listing is referenced, it must be live (don't leak draft ids).
  if p_listing_id is not null and not exists (
    select 1 from public.listings l where l.id = p_listing_id and public.listing_is_live(l.status)
  ) then
    p_listing_id := null;
  end if;

  insert into public.leads (type, stage, listing_id, name, email, phone, message, source)
  values (coalesce(p_type, 'inquiry'), 'new', p_listing_id, p_name, p_email, p_phone, p_message, 'website');
end; $$;

-- Sign an NDA for a listing, then receive its released documents. Records the
-- signature + a buyer lead, and returns the available documents so the browser
-- can reveal the download links. Returns [] if the listing has none released.
create or replace function public.sign_nda(
  p_listing_id uuid,
  p_name text,
  p_email text,
  p_phone text default null
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_lead_id uuid;
  v_docs jsonb;
begin
  if coalesce(trim(p_name), '') = '' or coalesce(trim(p_email), '') = '' then
    raise exception 'Name and email are required';
  end if;
  if not exists (
    select 1 from public.listings l where l.id = p_listing_id and public.listing_is_live(l.status)
  ) then
    raise exception 'Listing not found';
  end if;

  -- Upsert a buyer lead for this signer + listing so the broker sees them in
  -- the pipeline at the nda_signed stage.
  select id into v_lead_id from public.leads
    where email = p_email and listing_id = p_listing_id and type = 'buyer' limit 1;
  if v_lead_id is null then
    insert into public.leads (type, stage, listing_id, name, email, phone, message, source)
    values ('buyer', 'nda_signed', p_listing_id, p_name, p_email, p_phone, 'Signed NDA to access documents', 'website')
    returning id into v_lead_id;
  else
    update public.leads set stage = 'nda_signed', phone = coalesce(p_phone, phone), updated_at = now()
      where id = v_lead_id;
  end if;

  insert into public.ndas (listing_id, lead_id, signer_name, signer_email, signer_phone)
  values (p_listing_id, v_lead_id, p_name, p_email, p_phone);

  select coalesce(jsonb_agg(jsonb_build_object('name', d.name, 'file_url', d.file_url) order by d.sort_order), '[]'::jsonb)
    into v_docs
    from public.documents d
    where d.listing_id = p_listing_id and d.is_available;

  return v_docs;
end; $$;

-- Expose RPCs to the anonymous role.
grant execute on function public.submit_inquiry(text, text, text, text, uuid, lead_type) to anon, authenticated;
grant execute on function public.sign_nda(uuid, text, text, text) to anon, authenticated;


-- ===========================================================================
-- BEGIN 0002_brokers.sql
-- ===========================================================================

-- ============================================================================
-- Brokers as a first-class entity.
--
-- Previously the team was hardcoded in public/config.js. This promotes brokers
-- to real CMS data: managed in /admin, attributed on every listing ("Listed by"),
-- with their own public profile pages at /broker/<slug>.
--
-- Also lets an inquiry be routed to a specific broker (leads.broker_id), which
-- is how the contact form on a broker's profile page works.
-- ============================================================================

set check_function_bodies = off;

create table public.brokers (
  id          uuid primary key default gen_random_uuid(),
  slug        text not null unique,                 -- public URL: /broker/<slug>
  name        text not null,
  title       text,                                  -- "Licensed NYS Commercial & Residential Broker"
  license_no  text,
  phone       text,
  email       text,
  photo_url   text,
  bio         text,
  is_active   boolean not null default true,         -- inactive = hidden from the public site
  sort_order  int not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
alter table public.brokers enable row level security;
create trigger brokers_touch before update on public.brokers for each row execute function public.touch_updated_at();
create index on public.brokers (sort_order);

-- Active brokers are public (they're the firm's public face). Staff manage them.
create policy "brokers: public read active" on public.brokers for select
  using (is_active or public.is_staff());
create policy "brokers: staff write" on public.brokers for all
  using (public.is_staff()) with check (public.is_staff());

-- Attribute listings to a broker. Null = unassigned (falls back to firm contact).
alter table public.listings add column broker_id uuid references public.brokers(id) on delete set null;
create index on public.listings (broker_id);

-- Route a lead to a broker (e.g. the form on a broker's profile page).
alter table public.leads add column broker_id uuid references public.brokers(id) on delete set null;
create index on public.leads (broker_id);

-- ---------------------------------------------------------------------------
-- submit_inquiry gains p_broker_id. Signature changes, so drop + recreate.
-- ---------------------------------------------------------------------------
drop function if exists public.submit_inquiry(text, text, text, text, uuid, lead_type);

create or replace function public.submit_inquiry(
  p_name text,
  p_email text,
  p_message text,
  p_phone text default null,
  p_listing_id uuid default null,
  p_type lead_type default 'inquiry',
  p_broker_id uuid default null
) returns void
language plpgsql security definer set search_path = public as $$
declare v_broker uuid;
begin
  if coalesce(trim(p_name), '') = '' or coalesce(trim(p_email), '') = '' then
    raise exception 'Name and email are required';
  end if;

  -- If a listing is referenced, it must be live (don't leak draft ids).
  if p_listing_id is not null and not exists (
    select 1 from public.listings l where l.id = p_listing_id and public.listing_is_live(l.status)
  ) then
    p_listing_id := null;
  end if;

  -- Resolve the broker: explicit wins, else inherit from the listing.
  v_broker := p_broker_id;
  if v_broker is not null and not exists (
    select 1 from public.brokers b where b.id = v_broker and b.is_active
  ) then
    v_broker := null;
  end if;
  if v_broker is null and p_listing_id is not null then
    select l.broker_id into v_broker from public.listings l where l.id = p_listing_id;
  end if;

  insert into public.leads (type, stage, listing_id, broker_id, name, email, phone, message, source)
  values (coalesce(p_type, 'inquiry'), 'new', p_listing_id, v_broker, p_name, p_email, p_phone, p_message, 'website');
end; $$;

grant execute on function public.submit_inquiry(text, text, text, text, uuid, lead_type, uuid) to anon, authenticated;

-- sign_nda: also stamp the listing's broker onto the buyer lead it creates.
create or replace function public.sign_nda(
  p_listing_id uuid,
  p_name text,
  p_email text,
  p_phone text default null
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_lead_id uuid;
  v_broker  uuid;
  v_docs    jsonb;
begin
  if coalesce(trim(p_name), '') = '' or coalesce(trim(p_email), '') = '' then
    raise exception 'Name and email are required';
  end if;
  if not exists (
    select 1 from public.listings l where l.id = p_listing_id and public.listing_is_live(l.status)
  ) then
    raise exception 'Listing not found';
  end if;

  select broker_id into v_broker from public.listings where id = p_listing_id;

  select id into v_lead_id from public.leads
    where email = p_email and listing_id = p_listing_id and type = 'buyer' limit 1;
  if v_lead_id is null then
    insert into public.leads (type, stage, listing_id, broker_id, name, email, phone, message, source)
    values ('buyer', 'nda_signed', p_listing_id, v_broker, p_name, p_email, p_phone,
            'Signed NDA to access documents', 'website')
    returning id into v_lead_id;
  else
    update public.leads set stage = 'nda_signed', phone = coalesce(p_phone, phone), updated_at = now()
      where id = v_lead_id;
  end if;

  insert into public.ndas (listing_id, lead_id, signer_name, signer_email, signer_phone)
  values (p_listing_id, v_lead_id, p_name, p_email, p_phone);

  select coalesce(jsonb_agg(jsonb_build_object('name', d.name, 'file_url', d.file_url) order by d.sort_order), '[]'::jsonb)
    into v_docs
    from public.documents d
    where d.listing_id = p_listing_id and d.is_available;

  return v_docs;
end; $$;

grant execute on function public.sign_nda(uuid, text, text, text) to anon, authenticated;


-- ===========================================================================
-- BEGIN 0003_listing_brokers.sql
-- ===========================================================================

-- ============================================================================
-- Assign a listing to MANY agents (all / single / multiple).
--
-- Until now a listing had exactly one broker (listings.broker_id). This adds a
-- join table so a listing can be co-listed by any number of agents.
--
-- listings.broker_id is KEPT, and now means "primary agent": the one who owns
-- inbound enquiries. A lead has a single owner, so routing needs one. The join
-- table is who is *shown* on the listing; broker_id is who *gets the lead*.
-- The primary is always also present in listing_brokers (enforced below).
-- ============================================================================

set check_function_bodies = off;

create table if not exists public.listing_brokers (
  listing_id uuid not null references public.listings(id) on delete cascade,
  broker_id  uuid not null references public.brokers(id)  on delete cascade,
  created_at timestamptz not null default now(),
  primary key (listing_id, broker_id)
);
alter table public.listing_brokers enable row level security;
create index if not exists listing_brokers_broker_idx on public.listing_brokers (broker_id);

-- Readable wherever the parent listing is readable; staff manage.
drop policy if exists "listing_brokers: read where listing readable" on public.listing_brokers;
create policy "listing_brokers: read where listing readable" on public.listing_brokers for select
  using (exists (
    select 1 from public.listings l
    where l.id = listing_id and (public.listing_is_live(l.status) or public.is_staff())
  ));

drop policy if exists "listing_brokers: staff write" on public.listing_brokers;
create policy "listing_brokers: staff write" on public.listing_brokers for all
  using (public.is_staff()) with check (public.is_staff());

-- Backfill: every listing that already had a broker gets that assignment.
insert into public.listing_brokers (listing_id, broker_id)
select l.id, l.broker_id from public.listings l
where l.broker_id is not null
on conflict do nothing;

-- Keep the primary agent consistent: whenever listings.broker_id is set, make
-- sure that broker is also in the join table, so "assigned agents" can never
-- omit the person who receives the enquiries.
create or replace function public.sync_primary_broker()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.broker_id is not null then
    insert into public.listing_brokers (listing_id, broker_id)
    values (new.id, new.broker_id)
    on conflict do nothing;
  end if;
  return new;
end; $$;

drop trigger if exists listings_sync_primary_broker on public.listings;
create trigger listings_sync_primary_broker
  after insert or update of broker_id on public.listings
  for each row execute function public.sync_primary_broker();

-- If the primary agent is unassigned from a listing, promote another assigned
-- agent so enquiries still have an owner (or clear it if none are left).
create or replace function public.demote_unassigned_primary()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_next uuid;
begin
  if exists (select 1 from public.listings where id = old.listing_id and broker_id = old.broker_id) then
    select broker_id into v_next from public.listing_brokers
      where listing_id = old.listing_id and broker_id <> old.broker_id limit 1;
    update public.listings set broker_id = v_next where id = old.listing_id;
  end if;
  return old;
end; $$;

drop trigger if exists listing_brokers_demote_primary on public.listing_brokers;
create trigger listing_brokers_demote_primary
  after delete on public.listing_brokers
  for each row execute function public.demote_unassigned_primary();


-- ===========================================================================
-- BEGIN seed.sql
-- ===========================================================================

-- AUTO-GENERATED by tools/build-catalogue.mjs — do not hand-edit.
-- NGU Business Real Estate catalogue: brokers + listings.
-- Run AFTER 0001_init.sql and 0002_brokers.sql on a fresh project.
-- Photos use placeholder URLs (placehold.co); replace them from the admin console.

insert into public.brokers (slug, name, title, phone, email, bio, photo_url, is_active, sort_order)
values ('mary-lee', 'Mary Lee', 'Licensed NYS Commercial & Residential Broker · Business Sales Consultant', '718-737-6899', 'ngumarylee@gmail.com', 'Mary’s background spans finance, international relations, and small business management. She holds a degree in International Trade from a university in Korea, spent more than ten years with Korea’s Ministry of Foreign Affairs, and served three years at the United Nations as Attaché to the Korean Mission. She has also owned and operated small businesses herself.

A lifelong student of economics and finance, Mary has traded options and equities independently for over a decade. Outside of work she is an avid tennis player and daily jogger, and enjoys fishing and camping. She approaches every client relationship with integrity and persistence.',
  '/img/mary-lee.jpg', true, 0)
on conflict (slug) do nothing;

insert into public.brokers (slug, name, title, phone, email, bio, photo_url, is_active, sort_order)
values ('edward-lee', 'Edward Lee', 'Licensed NYS Salesperson · Business Sales Consultant', '347-614-0624', 'nguedwardlee@gmail.com', 'Edward holds a finance degree from Carnegie Mellon University. He previously worked in investment banking and Fortune 500 management consulting, where he focused on improving business operations and modernizing technology.

He began trading stocks in high school — his first purchase was Google — and now follows macroeconomic trends and quantitative strategies. He has built and owns three ventures: an AI customer analytics platform that analyzes complaints, surveys, and call transcripts to surface organizational pain points; a professional job board that lets candidates present themselves beyond a resume; and a CRM platform for beauty salon booking and discovery. A tennis enthusiast and singer, Edward values long client relationships and learning how each business really works.',
  '/img/edward-lee.jpg', true, 1)
on conflict (slug) do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('laundromat-bronx-long-lease', 'active', true, 'Laundromat – Large Space, Long Lease', 'Established 20+ years · primarily wholesale · 10-year lease remaining', 'Laundromat', 'Bronx', 'NY', 'Bronx',
  299000, 120000, 600000, 9700, null, 'Leased', '3,500 SF', '10-year lease remaining',
  'Exact address disclosed after NDA', '50 washers and 50 dryers. Primarily a wholesale operation with strong recurring commercial accounts.', 'A large, well-established Bronx laundromat operating for over 20 years with a primarily wholesale model that drives dependable, high-margin revenue. Roughly $600k in annual revenue and $120k in owner cash flow, with a long 10-year lease in place — a turnkey opportunity with room to grow the retail and drop-off side.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'laundromat-bronx-long-lease')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/1d6fb8/ffffff?text=Laundromat', 'Bronx, Bronx', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-bronx-long-lease' and b.slug = 'mary-lee'
on conflict do nothing;
with l as (select id from public.listings where slug = 'laundromat-bronx-long-lease')
insert into public.documents (listing_id, name, file_url, requires_nda, is_available, sort_order)
select l.id, v.name, v.url, true, true, v.so from l, (values
  ('Confidential Information Memorandum (CIM)', 'https://example.com/replace-with-storage-url.pdf', 0),
  ('Financials Summary', 'https://example.com/replace-with-storage-url-2.pdf', 1)
) as v(name, url, so)
where not exists (select 1 from public.documents d where d.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('laundromat-east-harlem-60-machines', 'sold', false, 'Large Laundromat – East Harlem', '60 machines · 2,000 SF plus full basement', 'Laundromat', 'East Harlem', 'NY', 'Manhattan',
  null, null, null, null, null, 'Leased', '2,000 SF + 2,000 SF basement', null,
  'Exact address disclosed after NDA', '60 machines (30 washers, 30 dryers). Prior laundry experience preferred for this operation.', 'A large East Harlem laundromat with 60 machines across a 2,000 SF store plus a full 2,000 SF basement. Established roughly four years.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'laundromat-east-harlem-60-machines')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/1d6fb8/ffffff?text=Laundromat', 'East Harlem, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-east-harlem-60-machines' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('laundromat-east-harlem-new-machines', 'sold', false, 'Laundromat – New Machines, Large Space', 'Absentee-run · employee profit sharing', 'Laundromat', 'East Harlem', 'NY', 'Manhattan',
  null, null, null, null, null, 'Leased', '2,000 SF + 2,000 SF basement', null,
  'Exact address disclosed after NDA', 'New machines installed about three years ago. Absentee-run with an employee profit-sharing arrangement.', 'A spacious East Harlem laundromat under the current owner for about seven years, with newer machines and an absentee model supported by employee profit sharing.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'laundromat-east-harlem-new-machines')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/1d6fb8/ffffff?text=Laundromat', 'East Harlem, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-east-harlem-new-machines' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('cafe-pizzeria-ues', 'sold', false, 'Café / Restaurant / Pizzeria – Upper East Side', 'Established 2004 · pre-pandemic revenue ~$3MM', 'Restaurant / Café', 'Upper East Side', 'NY', 'Manhattan',
  null, null, 3000000, null, 2004, 'Leased', '1,700 SF + 1,700 SF basement', null,
  'Exact address disclosed after NDA', 'Full café/restaurant/pizzeria build-out. Original owners retiring.', 'A long-running Upper East Side café, restaurant and pizzeria established in 2004 with pre-pandemic revenue near $3MM. Sold as the original owners retired.',
  (select id from public.brokers where slug = 'edward-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'cafe-pizzeria-ues')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/b7791f/ffffff?text=Restaurant%20%2F%20Caf%C3%A9', 'Upper East Side, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'cafe-pizzeria-ues' and b.slug = 'edward-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('dry-cleaners-lower-east-side', 'sold', false, 'Dry Cleaners – Lower East Side', 'Partial absentee · finance-district clientele', 'Dry Cleaners', 'Lower East Side', 'NY', 'Manhattan',
  null, null, null, 4600, null, 'Leased', null, null,
  'Exact address disclosed after NDA', 'Partial absentee operation serving a clientele of nearby finance employees.', 'A Lower East Side dry cleaner of 7+ years, run partially absentee, serving the surrounding finance workforce.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'dry-cleaners-lower-east-side')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/188f8f/ffffff?text=Dry%20Cleaners', 'Lower East Side, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'dry-cleaners-lower-east-side' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('dry-cleaners-bronx-large', 'sold', false, 'Dry Cleaners – Large Space', '35+ years · the only cleaner in the area', 'Dry Cleaners', 'Bronx', 'NY', 'Bronx',
  null, null, null, null, null, 'Leased', '1,500 SF', null,
  'Exact address disclosed after NDA', '1,500 SF plant with 4 staff. Effectively the only dry cleaner serving the immediate area.', 'A 35+ year Bronx dry cleaner enjoying a local monopoly, with a 1,500 SF space and a team of four.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'dry-cleaners-bronx-large')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/188f8f/ffffff?text=Dry%20Cleaners', 'Bronx, Bronx', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'dry-cleaners-bronx-large' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('laundromat-flushing-full-service', 'sold', false, 'Laundromat – Full Service, New Machines', '37 years established · commuter boulevard location', 'Laundromat', 'Flushing', 'NY', 'Queens',
  null, null, null, null, null, 'Leased', null, null,
  'Exact address disclosed after NDA', '35 new machines (under a year old). Full service including wash/fold and dry cleaning, on a busy commuter boulevard.', 'A 37-year full-service Queens laundromat on a commuter boulevard, refreshed with 35 nearly-new machines and offering wash/fold and dry cleaning.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'laundromat-flushing-full-service')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/1d6fb8/ffffff?text=Laundromat', 'Flushing, Queens', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-flushing-full-service' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('laundromat-queens-low-rent', 'sold', false, 'Laundromat – Long Lease, Low Rent', '50+ years · great starter business', 'Laundromat', 'Queens', 'NY', 'Queens',
  139000, 84000, 348000, 2800, null, 'Leased', '600 SF', '10+ year lease',
  'Exact address disclosed after NDA', 'Compact, efficient store with very low rent — an ideal first business.', 'A 50+ year Queens laundromat with a standout low rent of $2,800 and a 10+ year lease. About $348k revenue and $84k cash flow — a great starter opportunity.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'laundromat-queens-low-rent')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/1d6fb8/ffffff?text=Laundromat', 'Queens, Queens', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-queens-low-rent' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('dry-cleaners-bronx-yankee-stadium', 'sold', false, 'Dry Cleaners – Close to Yankee Stadium', '40+ years established · busy Bronx corridor', 'Dry Cleaners', 'Bronx', 'NY', 'Bronx',
  null, 100000, 400000, 3200, null, 'Leased', '900 SF + 900 SF basement', '7 years + 4-year option',
  'Exact address disclosed after NDA', 'Established plant near Yankee Stadium with a long operating history.', 'A busy Bronx dry cleaner near Yankee Stadium, 40+ years established (12 under the current owner), with ~$400k revenue and ~$100k cash flow.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'dry-cleaners-bronx-yankee-stadium')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/188f8f/ffffff?text=Dry%20Cleaners', 'Bronx, Bronx', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'dry-cleaners-bronx-yankee-stadium' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('laundromat-washington-heights-absentee', 'sold', false, 'Laundromat – Absentee, Long Lease', '14-year lease · expansion upside', 'Laundromat', 'Washington Heights', 'NY', 'Manhattan',
  399000, 118000, 455000, 8539, null, 'Leased', '1,000 SF', '14-year lease',
  'Exact address disclosed after NDA', 'Absentee-run with a long 14-year lease. Upside via wholesale, pickup/delivery, and dry cleaning.', 'An absentee-run Washington Heights laundromat with a 14-year lease, ~$455k revenue and ~$118k cash flow, and clear expansion paths into wholesale, pickup/delivery and dry cleaning.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'laundromat-washington-heights-absentee')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/1d6fb8/ffffff?text=Laundromat', 'Washington Heights, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-washington-heights-absentee' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('laundromat-harlem-low-rent', 'sold', false, 'Laundromat – Absentee, Low Rent, Long Lease', '15-year lease · coin and drop-off only', 'Laundromat', 'Harlem', 'NY', 'Manhattan',
  450000, 102000, 367000, 4637, null, 'Leased', '1,400 SF', '15-year lease',
  'Exact address disclosed after NDA', 'Absentee-run on a long 15-year lease with low rent. Currently coin and drop-off revenue only.', 'A Harlem laundromat with an exceptional 15-year lease and low rent, ~$367k revenue and ~$102k cash flow from coin and drop-off alone — room to add wholesale and delivery.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'laundromat-harlem-low-rent')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/1d6fb8/ffffff?text=Laundromat', 'Harlem, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-harlem-low-rent' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('laundromat-harlem-absentee', 'sold', false, 'Laundromat – Absentee, Long Lease', '11-year lease · wholesale upside', 'Laundromat', 'Harlem', 'NY', 'Manhattan',
  399000, 91000, 360000, 4819, null, 'Leased', '1,100 SF', '11-year lease',
  'Exact address disclosed after NDA', 'Absentee-run with an 11-year lease. Opportunity to grow via wholesale accounts.', 'An absentee Harlem laundromat with an 11-year lease, ~$360k revenue and ~$91k cash flow, with upside from adding wholesale.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'laundromat-harlem-absentee')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/1d6fb8/ffffff?text=Laundromat', 'Harlem, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-harlem-absentee' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('barbershop-ues', 'sold', false, 'Barbershop – Long Lease, Low Rent', '5 chairs · established Upper East Side clientele', 'Barbershop', 'Upper East Side', 'NY', 'Manhattan',
  95000, 84000, 119000, 2850, null, 'Leased', '500 SF', '8-year lease',
  'Exact address disclosed after NDA', 'Five-chair barbershop with a loyal, established customer base and low rent.', 'A profitable Upper East Side barbershop with five chairs, a loyal clientele, an 8-year lease and low rent — ~$119k revenue on ~$84k cash flow.',
  (select id from public.brokers where slug = 'edward-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'barbershop-ues')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/5b4b9f/ffffff?text=Barbershop', 'Upper East Side, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'barbershop-ues' and b.slug = 'edward-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('dry-cleaners-uws', 'sold', false, 'Dry Cleaners – Great Location, Long Lease', '30+ years established · Upper West Side', 'Dry Cleaners', 'Upper West Side', 'NY', 'Manhattan',
  79000, 70000, 270000, 6600, null, 'Leased', '500 SF + 500 SF basement', '10-year lease',
  'Exact address disclosed after NDA', 'Well-located Upper West Side plant with a long operating history.', 'A 30+ year Upper West Side dry cleaner (17 under the current owner) in a prime location, with a 10-year lease, ~$270k revenue and ~$70k cash flow.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'dry-cleaners-uws')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/188f8f/ffffff?text=Dry%20Cleaners', 'Upper West Side, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'dry-cleaners-uws' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('wash-fold-drop-store-ues', 'sold', false, 'Wash & Fold Laundry / Drop Store', 'Upper East Side · simple drop-store model', 'Laundromat', 'Upper East Side', 'NY', 'Manhattan',
  99000, 70000, 200000, 5600, null, 'Leased', '800 SF + 800 SF basement', '10-year lease',
  'Exact address disclosed after NDA', '8 washers and 8 dryers. Straightforward wash & fold / drop-store with no wholesale accounts.', 'An Upper East Side wash & fold and drop store, 35 years established, with 8 washers/dryers, a 10-year lease, ~$200k revenue and ~$70k cash flow — untapped wholesale potential.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'wash-fold-drop-store-ues')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/1d6fb8/ffffff?text=Laundromat', 'Upper East Side, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'wash-fold-drop-store-ues' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('laundromat-washington-heights-absentee-run', 'sold', false, 'Laundromat – Absentee Run', '31 machines · no real-estate tax', 'Laundromat', 'Washington Heights', 'NY', 'Manhattan',
  249000, 70000, 310000, 7000, null, 'Leased', '750 SF + 750 SF basement', '10-year lease',
  'Exact address disclosed after NDA', '31 machines (17 washers, 14 dryers). Absentee-run; rent includes no separate real-estate tax.', 'An absentee-run Washington Heights laundromat with 31 machines, a 10-year lease and ~$310k revenue on ~$70k cash flow.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'laundromat-washington-heights-absentee-run')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/1d6fb8/ffffff?text=Laundromat', 'Washington Heights, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-washington-heights-absentee-run' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('bagel-shop-cafe-bronx', 'sold', false, 'Bagel Shop / Café – Long Lease, Low Rent', 'Luxury residential building · ~$936k revenue', 'Restaurant / Café', 'Bronx', 'NY', 'Bronx',
  399000, null, 936000, 4600, null, 'Leased', '1,500 SF', '10 years + 5-year option',
  'Exact address disclosed after NDA', 'Located in a luxury residential building in an up-and-coming neighborhood. Low rent with no increase for two years and no real-estate tax.', 'A high-volume Bronx bagel shop and café in a luxury residential building, ~$936k in revenue, with a long lease and very favorable rent terms.',
  (select id from public.brokers where slug = 'edward-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'bagel-shop-cafe-bronx')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/b7791f/ffffff?text=Restaurant%20%2F%20Caf%C3%A9', 'Bronx, Bronx', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'bagel-shop-cafe-bronx' and b.slug = 'edward-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('laundromat-harlem-great-location', 'sold', false, 'Laundromat – Great Location, Long Lease', 'All-new equipment · ~$135k cash flow', 'Laundromat', 'Harlem', 'NY', 'Manhattan',
  749000, 135000, 445000, 14500, 2022, 'Leased', '1,800 SF + 1,800 SF basement', '10 years + 5-year option',
  'Exact address disclosed after NDA', '35 washers and 36 dryers, all new. Walk-in and drop-off only — no commercial accounts yet.', 'A modern, high-performing Harlem laundromat built out about two years ago with all-new equipment, ~$445k revenue and ~$135k cash flow from walk-in/drop-off alone — commercial accounts are the obvious next step.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'laundromat-harlem-great-location')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/1d6fb8/ffffff?text=Laundromat', 'Harlem, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-harlem-great-location' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('laundromat-astoria-large', 'sold', false, 'Laundromat – Astoria, Large Space, Long Lease', '52 newer machines · expansion potential', 'Laundromat', 'Astoria', 'NY', 'Queens',
  399000, 120000, 315600, 5400, null, 'Leased', '1,800 SF + 1,000 SF basement', 'New 10-year lease',
  'Exact address disclosed after NDA', '52 machines (26 washers, 26 dryers), about three years old. Upside via hotel, hospital and wholesale accounts.', 'A large Astoria laundromat with 52 newer machines, a fresh 10-year lease, ~$315k revenue and ~$120k cash flow, with strong commercial expansion potential.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'laundromat-astoria-large')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/1d6fb8/ffffff?text=Laundromat', 'Astoria, Queens', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-astoria-large' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('dry-cleaners-midtown-east', 'sold', false, 'Dry Cleaners – Great Location', 'Midtown East · pickup/delivery upside', 'Dry Cleaners', 'Midtown East', 'NY', 'Manhattan',
  99000, 95000, 394000, 7400, null, 'Leased', '400 SF + 400 SF basement', '5 years + 5-year option',
  'Exact address disclosed after NDA', 'Compact Midtown East plant. Growth opportunity through pickup/delivery and online ordering.', 'A well-located Midtown East dry cleaner, 21 years established (16 under the current owner), with ~$394k revenue and ~$95k cash flow — room to grow via pickup/delivery and online.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'dry-cleaners-midtown-east')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/188f8f/ffffff?text=Dry%20Cleaners', 'Midtown East, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'dry-cleaners-midtown-east' and b.slug = 'mary-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('greek-turkish-restaurant-tribeca', 'sold', false, 'Greek / Turkish Restaurant – Tribeca', '4.5-star rated · dine-in and delivery', 'Restaurant / Café', 'Tribeca', 'NY', 'Manhattan',
  179000, null, 720000, 10000, null, 'Leased', '1,000 SF + 1,000 SF basement', '10-year lease',
  'Exact address disclosed after NDA', 'Well-reviewed (4.5 stars) Mediterranean restaurant with dine-in and delivery. Marketing is the clear growth lever.', 'A well-reviewed Tribeca Greek/Turkish restaurant with ~$720k revenue, a 10-year lease and a 4.5-star reputation across dine-in and delivery.',
  (select id from public.brokers where slug = 'edward-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'greek-turkish-restaurant-tribeca')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/b7791f/ffffff?text=Restaurant%20%2F%20Caf%C3%A9', 'Tribeca, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'greek-turkish-restaurant-tribeca' and b.slug = 'edward-lee'
on conflict do nothing;

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, established_year, real_estate, building_sf, lease_expiration,
  location_note, facilities, description, broker_id)
values ('cafe-pizzeria-ues-flagship', 'sold', false, 'Café / Restaurant / Pizzeria – Upper East Side', 'Established 2004 · ~$3MM revenue', 'Restaurant / Café', 'Upper East Side', 'NY', 'Manhattan',
  999000, 280000, 3000000, 29200, 2004, 'Leased', '1,700 SF + 1,700 SF basement', '10-year lease',
  'Exact address disclosed after NDA', 'Flagship UES café/restaurant/pizzeria. Upside via staffing efficiency and menu diversification.', 'A flagship Upper East Side café, restaurant and pizzeria established in 2004, with ~$3MM revenue and ~$280k cash flow on a 10-year lease.',
  (select id from public.brokers where slug = 'edward-lee'))
on conflict (slug) do nothing;
with l as (select id from public.listings where slug = 'cafe-pizzeria-ues-flagship')
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, v.url, v.caption, v.is_primary, v.sort_order from l, (values
  ('https://placehold.co/1200x800/b7791f/ffffff?text=Restaurant%20%2F%20Caf%C3%A9', 'Upper East Side, Manhattan', true, 0)
) as v(url, caption, is_primary, sort_order)
where not exists (select 1 from public.listing_images i where i.listing_id = l.id);
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'cafe-pizzeria-ues-flagship' and b.slug = 'edward-lee'
on conflict do nothing;



