-- =============================================================================
-- NGU Business Real Estate - apply everything outstanding, in one go.
--
-- Paste this whole file into the Supabase SQL Editor and press Run.
-- Safe to re-run: every statement is guarded.
--
-- It does three things, in order:
--   1. Creates the "media" storage bucket, so the admin can upload photos.
--   2. Restores the deleted listings with their photos, and takes the
--      financial figures off closed deals (the active listing keeps its price).
--   3. Points the listings you already had at their real photographs.
-- =============================================================================

-- ===========================================================================
-- 1. STORAGE BUCKET (migrations/0004_storage.sql)
-- ===========================================================================

-- ============================================================================
-- Storage bucket for uploaded photos (broker headshots, listing photos).
--
-- Until now the admin could only accept a URL typed by hand, which meant
-- photos had to be hosted somewhere else first. This creates a public bucket
-- so the admin can upload a file directly.
--
-- Public read: these images are displayed on the public site, so the bucket is
-- readable by anyone. Writes are restricted to signed-in staff.
-- ============================================================================

insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do update set public = true;

-- Anyone may read (the site shows these images).
drop policy if exists "media: public read" on storage.objects;
create policy "media: public read" on storage.objects for select
  using (bucket_id = 'media');

-- Only staff may add, replace or remove files.
drop policy if exists "media: staff insert" on storage.objects;
create policy "media: staff insert" on storage.objects for insert
  with check (bucket_id = 'media' and public.is_staff());

drop policy if exists "media: staff update" on storage.objects;
create policy "media: staff update" on storage.objects for update
  using (bucket_id = 'media' and public.is_staff())
  with check (bucket_id = 'media' and public.is_staff());

drop policy if exists "media: staff delete" on storage.objects;
create policy "media: staff delete" on storage.objects for delete
  using (bucket_id = 'media' and public.is_staff());


-- ===========================================================================
-- 2. RESTORE LISTINGS + REMOVE FIGURES (restore_listings.sql)
-- ===========================================================================

-- Restore deleted listings, and take financial figures off closed deals.
-- Generated by tools/build-catalogue.mjs. Safe to re-run.
--
-- Two things happen here:
--   1. Any listing missing from the database is re-inserted, with its photo.
--   2. Every SOLD listing has its figures cleared - asking price, cash flow,
--      gross revenue, rent and lease - and its headline and description
--      replaced with wording that does not quote figures. Clearing the columns
--      alone would leave the same numbers sitting in the paragraph beneath.
--
-- ACTIVE listings keep their figures and their wording untouched.

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('laundromat-bronx-long-lease', 'active', true, 'Laundromat – Large Space, Long Lease', 'Established 20+ years · primarily wholesale · 10-year lease remaining', 'Laundromat', 'Bronx', 'NY', 'Bronx',
  299000, 120000, 600000, 9700, '10-year lease remaining',
  null, 'Leased', '3,500 SF', 'Exact address disclosed after NDA', '50 washers and 50 dryers. Primarily a wholesale operation with strong recurring commercial accounts.', 'A large, well-established Bronx laundromat operating for over 20 years with a primarily wholesale model that drives dependable, high-margin revenue. Roughly $600k in annual revenue and $120k in owner cash flow, with a long 10-year lease in place — a turnkey opportunity with room to grow the retail and drop-off side.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-bronx-long-lease' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-bronx-long-lease.jpg', 'Bronx, Bronx', true, 0
from public.listings l where l.slug = 'laundromat-bronx-long-lease'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('laundromat-east-harlem-60-machines', 'sold', false, 'Large Laundromat – East Harlem', '60 machines · 2,000 SF plus full basement', 'Laundromat', 'East Harlem', 'NY', 'Manhattan',
  null, null, null, null, null,
  null, 'Leased', '2,000 SF + 2,000 SF basement', 'Exact address disclosed after NDA', '60 machines (30 washers, 30 dryers). Prior laundry experience preferred for this operation.', 'A large East Harlem laundromat with 60 machines across a 2,000 SF store plus a full 2,000 SF basement. Established roughly four years.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = '60 machines · 2,000 SF plus full basement', description = 'A large East Harlem laundromat with 60 machines across a 2,000 SF store plus a full 2,000 SF basement. Established roughly four years.'
where slug = 'laundromat-east-harlem-60-machines';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-east-harlem-60-machines' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-east-harlem-60-machines.jpg', 'East Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-east-harlem-60-machines'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('laundromat-east-harlem-new-machines', 'sold', false, 'Laundromat – New Machines, Large Space', 'Absentee-run · employee profit sharing', 'Laundromat', 'East Harlem', 'NY', 'Manhattan',
  null, null, null, null, null,
  null, 'Leased', '2,000 SF + 2,000 SF basement', 'Exact address disclosed after NDA', 'New machines installed about three years ago. Absentee-run with an employee profit-sharing arrangement.', 'A spacious East Harlem laundromat under the current owner for about seven years, with newer machines and an absentee model supported by employee profit sharing.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = 'Absentee-run · employee profit sharing', description = 'A spacious East Harlem laundromat under the current owner for about seven years, with newer machines and an absentee model supported by employee profit sharing.'
where slug = 'laundromat-east-harlem-new-machines';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-east-harlem-new-machines' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-east-harlem-new-machines.jpg', 'East Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-east-harlem-new-machines'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('cafe-pizzeria-ues', 'sold', false, 'Café / Restaurant / Pizzeria – Upper East Side', 'Established 2004 · original owners retiring', 'Restaurant / Café', 'Upper East Side', 'NY', 'Manhattan',
  null, null, null, null, null,
  2004, 'Leased', '1,700 SF + 1,700 SF basement', 'Exact address disclosed after NDA', 'Full café/restaurant/pizzeria build-out. Original owners retiring.', 'A long-running Upper East Side café, restaurant and pizzeria established in 2004 with a strong pre-pandemic trading history. Sold as the original owners retired.',
  (select id from public.brokers where slug = 'edward-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = 'Established 2004 · original owners retiring', description = 'A long-running Upper East Side café, restaurant and pizzeria established in 2004 with a strong pre-pandemic trading history. Sold as the original owners retired.'
where slug = 'cafe-pizzeria-ues';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'cafe-pizzeria-ues' and b.slug = 'edward-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/cafe-pizzeria-ues.jpg', 'Upper East Side, Manhattan', true, 0
from public.listings l where l.slug = 'cafe-pizzeria-ues'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('dry-cleaners-lower-east-side', 'sold', false, 'Dry Cleaners – Lower East Side', 'Partial absentee · finance-district clientele', 'Dry Cleaners', 'Lower East Side', 'NY', 'Manhattan',
  null, null, null, null, null,
  null, 'Leased', null, 'Exact address disclosed after NDA', 'Partial absentee operation serving a clientele of nearby finance employees.', 'A Lower East Side dry cleaner of 7+ years, run partially absentee, serving the surrounding finance workforce.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = 'Partial absentee · finance-district clientele', description = 'A Lower East Side dry cleaner of 7+ years, run partially absentee, serving the surrounding finance workforce.'
where slug = 'dry-cleaners-lower-east-side';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'dry-cleaners-lower-east-side' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-lower-east-side.jpg', 'Lower East Side, Manhattan', true, 0
from public.listings l where l.slug = 'dry-cleaners-lower-east-side'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('dry-cleaners-bronx-large', 'sold', false, 'Dry Cleaners – Large Space', '35+ years · the only cleaner in the area', 'Dry Cleaners', 'Bronx', 'NY', 'Bronx',
  null, null, null, null, null,
  null, 'Leased', '1,500 SF', 'Exact address disclosed after NDA', '1,500 SF plant with 4 staff. Effectively the only dry cleaner serving the immediate area.', 'A 35+ year Bronx dry cleaner enjoying a local monopoly, with a 1,500 SF space and a team of four.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = '35+ years · the only cleaner in the area', description = 'A 35+ year Bronx dry cleaner enjoying a local monopoly, with a 1,500 SF space and a team of four.'
where slug = 'dry-cleaners-bronx-large';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'dry-cleaners-bronx-large' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-bronx-large.jpg', 'Bronx, Bronx', true, 0
from public.listings l where l.slug = 'dry-cleaners-bronx-large'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('laundromat-flushing-full-service', 'sold', false, 'Laundromat – Full Service, New Machines', '37 years established · commuter boulevard location', 'Laundromat', 'Flushing', 'NY', 'Queens',
  null, null, null, null, null,
  null, 'Leased', null, 'Exact address disclosed after NDA', '35 new machines (under a year old). Full service including wash/fold and dry cleaning, on a busy commuter boulevard.', 'A 37-year full-service Queens laundromat on a commuter boulevard, refreshed with 35 nearly-new machines and offering wash/fold and dry cleaning.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = '37 years established · commuter boulevard location', description = 'A 37-year full-service Queens laundromat on a commuter boulevard, refreshed with 35 nearly-new machines and offering wash/fold and dry cleaning.'
where slug = 'laundromat-flushing-full-service';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-flushing-full-service' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-flushing-full-service.jpg', 'Flushing, Queens', true, 0
from public.listings l where l.slug = 'laundromat-flushing-full-service'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('laundromat-queens-low-rent', 'sold', false, 'Laundromat – Long Lease, Low Rent', '50+ years · great starter business', 'Laundromat', 'Queens', 'NY', 'Queens',
  null, null, null, null, null,
  null, 'Leased', '600 SF', 'Exact address disclosed after NDA', 'Compact, efficient store with very low rent — an ideal first business.', 'A 50+ year Queens laundromat with a standout low rent and a 10+ year lease in place — an ideal first business.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = '50+ years · great starter business', description = 'A 50+ year Queens laundromat with a standout low rent and a 10+ year lease in place — an ideal first business.'
where slug = 'laundromat-queens-low-rent';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-queens-low-rent' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-queens-low-rent.jpg', 'Queens, Queens', true, 0
from public.listings l where l.slug = 'laundromat-queens-low-rent'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('dry-cleaners-bronx-yankee-stadium', 'sold', false, 'Dry Cleaners – Close to Yankee Stadium', '40+ years established · busy Bronx corridor', 'Dry Cleaners', 'Bronx', 'NY', 'Bronx',
  null, null, null, null, null,
  null, 'Leased', '900 SF + 900 SF basement', 'Exact address disclosed after NDA', 'Established plant near Yankee Stadium with a long operating history.', 'A busy Bronx dry cleaner near Yankee Stadium, 40+ years established (12 under the current owner), with a steady local trade.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = '40+ years established · busy Bronx corridor', description = 'A busy Bronx dry cleaner near Yankee Stadium, 40+ years established (12 under the current owner), with a steady local trade.'
where slug = 'dry-cleaners-bronx-yankee-stadium';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'dry-cleaners-bronx-yankee-stadium' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-bronx-yankee-stadium.jpg', 'Bronx, Bronx', true, 0
from public.listings l where l.slug = 'dry-cleaners-bronx-yankee-stadium'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('laundromat-washington-heights-absentee', 'sold', false, 'Laundromat – Absentee, Long Lease', '14-year lease · expansion upside', 'Laundromat', 'Washington Heights', 'NY', 'Manhattan',
  null, null, null, null, null,
  null, 'Leased', '1,000 SF', 'Exact address disclosed after NDA', 'Absentee-run with a long 14-year lease. Upside via wholesale, pickup/delivery, and dry cleaning.', 'An absentee-run Washington Heights laundromat with a long 14-year lease, and clear expansion paths into wholesale, pickup/delivery and dry cleaning.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = '14-year lease · expansion upside', description = 'An absentee-run Washington Heights laundromat with a long 14-year lease, and clear expansion paths into wholesale, pickup/delivery and dry cleaning.'
where slug = 'laundromat-washington-heights-absentee';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-washington-heights-absentee' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-washington-heights-absentee.jpg', 'Washington Heights, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-washington-heights-absentee'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('laundromat-harlem-low-rent', 'sold', false, 'Laundromat – Absentee, Low Rent, Long Lease', '15-year lease · coin and drop-off only', 'Laundromat', 'Harlem', 'NY', 'Manhattan',
  null, null, null, null, null,
  null, 'Leased', '1,400 SF', 'Exact address disclosed after NDA', 'Absentee-run on a long 15-year lease with low rent. Currently coin and drop-off revenue only.', 'A Harlem laundromat with an exceptional 15-year lease and low rent, trading on coin and drop-off alone — room to add wholesale and delivery.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = '15-year lease · coin and drop-off only', description = 'A Harlem laundromat with an exceptional 15-year lease and low rent, trading on coin and drop-off alone — room to add wholesale and delivery.'
where slug = 'laundromat-harlem-low-rent';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-harlem-low-rent' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-harlem-low-rent.jpg', 'Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-harlem-low-rent'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('laundromat-harlem-absentee', 'sold', false, 'Laundromat – Absentee, Long Lease', '11-year lease · wholesale upside', 'Laundromat', 'Harlem', 'NY', 'Manhattan',
  null, null, null, null, null,
  null, 'Leased', '1,100 SF', 'Exact address disclosed after NDA', 'Absentee-run with an 11-year lease. Opportunity to grow via wholesale accounts.', 'An absentee Harlem laundromat with an 11-year lease and upside from adding wholesale accounts.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = '11-year lease · wholesale upside', description = 'An absentee Harlem laundromat with an 11-year lease and upside from adding wholesale accounts.'
where slug = 'laundromat-harlem-absentee';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-harlem-absentee' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-harlem-absentee.jpg', 'Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-harlem-absentee'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('barbershop-ues', 'sold', false, 'Barbershop – Long Lease, Low Rent', '5 chairs · established Upper East Side clientele', 'Barbershop', 'Upper East Side', 'NY', 'Manhattan',
  null, null, null, null, null,
  null, 'Leased', '500 SF', 'Exact address disclosed after NDA', 'Five-chair barbershop with a loyal, established customer base and low rent.', 'A profitable Upper East Side barbershop with five chairs, a loyal clientele, an 8-year lease and low rent.',
  (select id from public.brokers where slug = 'edward-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = '5 chairs · established Upper East Side clientele', description = 'A profitable Upper East Side barbershop with five chairs, a loyal clientele, an 8-year lease and low rent.'
where slug = 'barbershop-ues';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'barbershop-ues' and b.slug = 'edward-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/barbershop-ues.jpg', 'Upper East Side, Manhattan', true, 0
from public.listings l where l.slug = 'barbershop-ues'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('dry-cleaners-uws', 'sold', false, 'Dry Cleaners – Great Location, Long Lease', '30+ years established · Upper West Side', 'Dry Cleaners', 'Upper West Side', 'NY', 'Manhattan',
  null, null, null, null, null,
  null, 'Leased', '500 SF + 500 SF basement', 'Exact address disclosed after NDA', 'Well-located Upper West Side plant with a long operating history.', 'A 30+ year Upper West Side dry cleaner (17 under the current owner) in a prime location, with a 10-year lease.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = '30+ years established · Upper West Side', description = 'A 30+ year Upper West Side dry cleaner (17 under the current owner) in a prime location, with a 10-year lease.'
where slug = 'dry-cleaners-uws';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'dry-cleaners-uws' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-uws.jpg', 'Upper West Side, Manhattan', true, 0
from public.listings l where l.slug = 'dry-cleaners-uws'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('wash-fold-drop-store-ues', 'sold', false, 'Wash & Fold Laundry / Drop Store', 'Upper East Side · simple drop-store model', 'Laundromat', 'Upper East Side', 'NY', 'Manhattan',
  null, null, null, null, null,
  null, 'Leased', '800 SF + 800 SF basement', 'Exact address disclosed after NDA', '8 washers and 8 dryers. Straightforward wash & fold / drop-store with no wholesale accounts.', 'An Upper East Side wash & fold and drop store, 35 years established, with eight washers and dryers and a 10-year lease — untapped wholesale potential.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = 'Upper East Side · simple drop-store model', description = 'An Upper East Side wash & fold and drop store, 35 years established, with eight washers and dryers and a 10-year lease — untapped wholesale potential.'
where slug = 'wash-fold-drop-store-ues';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'wash-fold-drop-store-ues' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/wash-fold-drop-store-ues.jpg', 'Upper East Side, Manhattan', true, 0
from public.listings l where l.slug = 'wash-fold-drop-store-ues'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('laundromat-washington-heights-absentee-run', 'sold', false, 'Laundromat – Absentee Run', '31 machines · no real-estate tax', 'Laundromat', 'Washington Heights', 'NY', 'Manhattan',
  null, null, null, null, null,
  null, 'Leased', '750 SF + 750 SF basement', 'Exact address disclosed after NDA', '31 machines (17 washers, 14 dryers). Absentee-run; rent includes no separate real-estate tax.', 'An absentee-run Washington Heights laundromat with 31 machines and a 10-year lease.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = '31 machines · no real-estate tax', description = 'An absentee-run Washington Heights laundromat with 31 machines and a 10-year lease.'
where slug = 'laundromat-washington-heights-absentee-run';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-washington-heights-absentee-run' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-washington-heights-absentee-run.jpg', 'Washington Heights, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-washington-heights-absentee-run'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('bagel-shop-cafe-bronx', 'sold', false, 'Bagel Shop / Café – Long Lease, Low Rent', 'Luxury residential building · long lease, low rent', 'Restaurant / Café', 'Bronx', 'NY', 'Bronx',
  null, null, null, null, null,
  null, 'Leased', '1,500 SF', 'Exact address disclosed after NDA', 'Located in a luxury residential building in an up-and-coming neighborhood. Low rent with no increase for two years and no real-estate tax.', 'A high-volume Bronx bagel shop and café in a luxury residential building, with a long lease and very favorable rent terms.',
  (select id from public.brokers where slug = 'edward-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = 'Luxury residential building · long lease, low rent', description = 'A high-volume Bronx bagel shop and café in a luxury residential building, with a long lease and very favorable rent terms.'
where slug = 'bagel-shop-cafe-bronx';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'bagel-shop-cafe-bronx' and b.slug = 'edward-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/bagel-shop-cafe-bronx.jpg', 'Bronx, Bronx', true, 0
from public.listings l where l.slug = 'bagel-shop-cafe-bronx'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('laundromat-harlem-great-location', 'sold', false, 'Laundromat – Great Location, Long Lease', 'All-new equipment · walk-in and drop-off', 'Laundromat', 'Harlem', 'NY', 'Manhattan',
  null, null, null, null, null,
  2022, 'Leased', '1,800 SF + 1,800 SF basement', 'Exact address disclosed after NDA', '35 washers and 36 dryers, all new. Walk-in and drop-off only — no commercial accounts yet.', 'A modern, high-performing Harlem laundromat built out about two years ago with all-new equipment, trading on walk-in and drop-off alone — commercial accounts are the obvious next step.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = 'All-new equipment · walk-in and drop-off', description = 'A modern, high-performing Harlem laundromat built out about two years ago with all-new equipment, trading on walk-in and drop-off alone — commercial accounts are the obvious next step.'
where slug = 'laundromat-harlem-great-location';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-harlem-great-location' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-harlem-great-location.jpg', 'Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-harlem-great-location'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('laundromat-astoria-large', 'sold', false, 'Laundromat – Astoria, Large Space, Long Lease', '52 newer machines · expansion potential', 'Laundromat', 'Astoria', 'NY', 'Queens',
  null, null, null, null, null,
  null, 'Leased', '1,800 SF + 1,000 SF basement', 'Exact address disclosed after NDA', '52 machines (26 washers, 26 dryers), about three years old. Upside via hotel, hospital and wholesale accounts.', 'A large Astoria laundromat with 52 newer machines and a fresh 10-year lease, with strong commercial expansion potential.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = '52 newer machines · expansion potential', description = 'A large Astoria laundromat with 52 newer machines and a fresh 10-year lease, with strong commercial expansion potential.'
where slug = 'laundromat-astoria-large';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'laundromat-astoria-large' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-astoria-large.jpg', 'Astoria, Queens', true, 0
from public.listings l where l.slug = 'laundromat-astoria-large'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('dry-cleaners-midtown-east', 'sold', false, 'Dry Cleaners – Great Location', 'Midtown East · pickup/delivery upside', 'Dry Cleaners', 'Midtown East', 'NY', 'Manhattan',
  null, null, null, null, null,
  null, 'Leased', '400 SF + 400 SF basement', 'Exact address disclosed after NDA', 'Compact Midtown East plant. Growth opportunity through pickup/delivery and online ordering.', 'A well-located Midtown East dry cleaner, 21 years established (16 under the current owner) — room to grow via pickup/delivery and online.',
  (select id from public.brokers where slug = 'mary-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = 'Midtown East · pickup/delivery upside', description = 'A well-located Midtown East dry cleaner, 21 years established (16 under the current owner) — room to grow via pickup/delivery and online.'
where slug = 'dry-cleaners-midtown-east';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'dry-cleaners-midtown-east' and b.slug = 'mary-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-midtown-east.jpg', 'Midtown East, Manhattan', true, 0
from public.listings l where l.slug = 'dry-cleaners-midtown-east'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('greek-turkish-restaurant-tribeca', 'sold', false, 'Greek / Turkish Restaurant – Tribeca', '4.5-star rated · dine-in and delivery', 'Restaurant / Café', 'Tribeca', 'NY', 'Manhattan',
  null, null, null, null, null,
  null, 'Leased', '1,000 SF + 1,000 SF basement', 'Exact address disclosed after NDA', 'Well-reviewed (4.5 stars) Mediterranean restaurant with dine-in and delivery. Marketing is the clear growth lever.', 'A well-reviewed Tribeca Greek/Turkish restaurant with a 10-year lease and a 4.5-star reputation across dine-in and delivery.',
  (select id from public.brokers where slug = 'edward-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = '4.5-star rated · dine-in and delivery', description = 'A well-reviewed Tribeca Greek/Turkish restaurant with a 10-year lease and a 4.5-star reputation across dine-in and delivery.'
where slug = 'greek-turkish-restaurant-tribeca';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'greek-turkish-restaurant-tribeca' and b.slug = 'edward-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/greek-turkish-restaurant-tribeca.jpg', 'Tribeca, Manhattan', true, 0
from public.listings l where l.slug = 'greek-turkish-restaurant-tribeca'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

insert into public.listings (slug, status, is_featured, title, headline, category, city, state, county,
  asking_price, cash_flow, gross_revenue, rent, lease_expiration,
  established_year, real_estate, building_sf, location_note, facilities, description, broker_id)
values ('cafe-pizzeria-ues-flagship', 'sold', false, 'Café / Restaurant / Pizzeria – Upper East Side', 'Established 2004 · flagship location', 'Restaurant / Café', 'Upper East Side', 'NY', 'Manhattan',
  null, null, null, null, null,
  2004, 'Leased', '1,700 SF + 1,700 SF basement', 'Exact address disclosed after NDA', 'Flagship UES café/restaurant/pizzeria. Upside via staffing efficiency and menu diversification.', 'A flagship Upper East Side café, restaurant and pizzeria established in 2004, on a 10-year lease.',
  (select id from public.brokers where slug = 'edward-lee'))
on conflict (slug) do nothing;
-- already present? strip its figures and refresh the wording
update public.listings set
  asking_price = null, cash_flow = null, gross_revenue = null, rent = null, lease_expiration = null,
  headline = 'Established 2004 · flagship location', description = 'A flagship Upper East Side café, restaurant and pizzeria established in 2004, on a 10-year lease.'
where slug = 'cafe-pizzeria-ues-flagship';
insert into public.listing_brokers (listing_id, broker_id)
select l.id, b.id from public.listings l, public.brokers b
where l.slug = 'cafe-pizzeria-ues-flagship' and b.slug = 'edward-lee'
on conflict do nothing;
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/cafe-pizzeria-ues-flagship.jpg', 'Upper East Side, Manhattan', true, 0
from public.listings l where l.slug = 'cafe-pizzeria-ues-flagship'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);



-- ===========================================================================
-- 3. REAL PHOTOS (listing_photos.sql)
-- ===========================================================================

-- Point existing listing photos at the real images committed under
-- public/img/listings/. Generated by tools/build-catalogue.mjs.
-- Safe to re-run. Listings that are not present are simply skipped.

update public.listing_images i set url = '/img/listings/laundromat-bronx-long-lease.jpg', caption = 'Bronx, Bronx'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-bronx-long-lease';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-bronx-long-lease.jpg', 'Bronx, Bronx', true, 0
from public.listings l where l.slug = 'laundromat-bronx-long-lease'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-east-harlem-60-machines.jpg', caption = 'East Harlem, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-east-harlem-60-machines';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-east-harlem-60-machines.jpg', 'East Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-east-harlem-60-machines'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-east-harlem-new-machines.jpg', caption = 'East Harlem, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-east-harlem-new-machines';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-east-harlem-new-machines.jpg', 'East Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-east-harlem-new-machines'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/cafe-pizzeria-ues.jpg', caption = 'Upper East Side, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'cafe-pizzeria-ues';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/cafe-pizzeria-ues.jpg', 'Upper East Side, Manhattan', true, 0
from public.listings l where l.slug = 'cafe-pizzeria-ues'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/dry-cleaners-lower-east-side.jpg', caption = 'Lower East Side, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'dry-cleaners-lower-east-side';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-lower-east-side.jpg', 'Lower East Side, Manhattan', true, 0
from public.listings l where l.slug = 'dry-cleaners-lower-east-side'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/dry-cleaners-bronx-large.jpg', caption = 'Bronx, Bronx'
  from public.listings l where i.listing_id = l.id and l.slug = 'dry-cleaners-bronx-large';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-bronx-large.jpg', 'Bronx, Bronx', true, 0
from public.listings l where l.slug = 'dry-cleaners-bronx-large'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-flushing-full-service.jpg', caption = 'Flushing, Queens'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-flushing-full-service';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-flushing-full-service.jpg', 'Flushing, Queens', true, 0
from public.listings l where l.slug = 'laundromat-flushing-full-service'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-queens-low-rent.jpg', caption = 'Queens, Queens'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-queens-low-rent';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-queens-low-rent.jpg', 'Queens, Queens', true, 0
from public.listings l where l.slug = 'laundromat-queens-low-rent'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/dry-cleaners-bronx-yankee-stadium.jpg', caption = 'Bronx, Bronx'
  from public.listings l where i.listing_id = l.id and l.slug = 'dry-cleaners-bronx-yankee-stadium';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-bronx-yankee-stadium.jpg', 'Bronx, Bronx', true, 0
from public.listings l where l.slug = 'dry-cleaners-bronx-yankee-stadium'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-washington-heights-absentee.jpg', caption = 'Washington Heights, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-washington-heights-absentee';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-washington-heights-absentee.jpg', 'Washington Heights, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-washington-heights-absentee'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-harlem-low-rent.jpg', caption = 'Harlem, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-harlem-low-rent';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-harlem-low-rent.jpg', 'Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-harlem-low-rent'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-harlem-absentee.jpg', caption = 'Harlem, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-harlem-absentee';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-harlem-absentee.jpg', 'Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-harlem-absentee'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/barbershop-ues.jpg', caption = 'Upper East Side, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'barbershop-ues';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/barbershop-ues.jpg', 'Upper East Side, Manhattan', true, 0
from public.listings l where l.slug = 'barbershop-ues'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/dry-cleaners-uws.jpg', caption = 'Upper West Side, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'dry-cleaners-uws';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-uws.jpg', 'Upper West Side, Manhattan', true, 0
from public.listings l where l.slug = 'dry-cleaners-uws'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/wash-fold-drop-store-ues.jpg', caption = 'Upper East Side, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'wash-fold-drop-store-ues';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/wash-fold-drop-store-ues.jpg', 'Upper East Side, Manhattan', true, 0
from public.listings l where l.slug = 'wash-fold-drop-store-ues'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-washington-heights-absentee-run.jpg', caption = 'Washington Heights, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-washington-heights-absentee-run';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-washington-heights-absentee-run.jpg', 'Washington Heights, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-washington-heights-absentee-run'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/bagel-shop-cafe-bronx.jpg', caption = 'Bronx, Bronx'
  from public.listings l where i.listing_id = l.id and l.slug = 'bagel-shop-cafe-bronx';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/bagel-shop-cafe-bronx.jpg', 'Bronx, Bronx', true, 0
from public.listings l where l.slug = 'bagel-shop-cafe-bronx'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-harlem-great-location.jpg', caption = 'Harlem, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-harlem-great-location';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-harlem-great-location.jpg', 'Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-harlem-great-location'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-astoria-large.jpg', caption = 'Astoria, Queens'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-astoria-large';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-astoria-large.jpg', 'Astoria, Queens', true, 0
from public.listings l where l.slug = 'laundromat-astoria-large'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/dry-cleaners-midtown-east.jpg', caption = 'Midtown East, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'dry-cleaners-midtown-east';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-midtown-east.jpg', 'Midtown East, Manhattan', true, 0
from public.listings l where l.slug = 'dry-cleaners-midtown-east'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/greek-turkish-restaurant-tribeca.jpg', caption = 'Tribeca, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'greek-turkish-restaurant-tribeca';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/greek-turkish-restaurant-tribeca.jpg', 'Tribeca, Manhattan', true, 0
from public.listings l where l.slug = 'greek-turkish-restaurant-tribeca'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/cafe-pizzeria-ues-flagship.jpg', caption = 'Upper East Side, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'cafe-pizzeria-ues-flagship';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/cafe-pizzeria-ues-flagship.jpg', 'Upper East Side, Manhattan', true, 0
from public.listings l where l.slug = 'cafe-pizzeria-ues-flagship'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);



