-- Point existing listing photos at the real images committed under
-- public/img/listings/. Generated by tools/build-catalogue.mjs.
-- Safe to re-run. Listings that are not present are simply skipped.

update public.listing_images i set url = '/img/listings/laundromat-bronx-long-lease.jpg', caption = 'Bronx, Bronx'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-bronx-long-lease';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-bronx-long-lease.jpg', 'Bronx, Bronx', true, 0
from public.listings l where l.slug = 'laundromat-bronx-long-lease'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-east-harlem-60-machines.jpg', caption = 'East Harlem, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-east-harlem-60-machines';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-east-harlem-60-machines.jpg', 'East Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-east-harlem-60-machines'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-east-harlem-new-machines.jpg', caption = 'East Harlem, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-east-harlem-new-machines';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-east-harlem-new-machines.jpg', 'East Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-east-harlem-new-machines'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/cafe-pizzeria-ues.jpg', caption = 'Upper East Side, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'cafe-pizzeria-ues';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/cafe-pizzeria-ues.jpg', 'Upper East Side, Manhattan', true, 0
from public.listings l where l.slug = 'cafe-pizzeria-ues'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/dry-cleaners-lower-east-side.jpg', caption = 'Lower East Side, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'dry-cleaners-lower-east-side';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-lower-east-side.jpg', 'Lower East Side, Manhattan', true, 0
from public.listings l where l.slug = 'dry-cleaners-lower-east-side'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/dry-cleaners-bronx-large.jpg', caption = 'Bronx, Bronx'
  from public.listings l where i.listing_id = l.id and l.slug = 'dry-cleaners-bronx-large';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-bronx-large.jpg', 'Bronx, Bronx', true, 0
from public.listings l where l.slug = 'dry-cleaners-bronx-large'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-flushing-full-service.jpg', caption = 'Flushing, Queens'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-flushing-full-service';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-flushing-full-service.jpg', 'Flushing, Queens', true, 0
from public.listings l where l.slug = 'laundromat-flushing-full-service'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-queens-low-rent.jpg', caption = 'Queens, Queens'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-queens-low-rent';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-queens-low-rent.jpg', 'Queens, Queens', true, 0
from public.listings l where l.slug = 'laundromat-queens-low-rent'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/dry-cleaners-bronx-yankee-stadium.jpg', caption = 'Bronx, Bronx'
  from public.listings l where i.listing_id = l.id and l.slug = 'dry-cleaners-bronx-yankee-stadium';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-bronx-yankee-stadium.jpg', 'Bronx, Bronx', true, 0
from public.listings l where l.slug = 'dry-cleaners-bronx-yankee-stadium'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-washington-heights-absentee.jpg', caption = 'Washington Heights, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-washington-heights-absentee';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-washington-heights-absentee.jpg', 'Washington Heights, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-washington-heights-absentee'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-harlem-low-rent.jpg', caption = 'Harlem, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-harlem-low-rent';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-harlem-low-rent.jpg', 'Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-harlem-low-rent'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-harlem-absentee.jpg', caption = 'Harlem, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-harlem-absentee';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-harlem-absentee.jpg', 'Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-harlem-absentee'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/barbershop-ues.jpg', caption = 'Upper East Side, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'barbershop-ues';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/barbershop-ues.jpg', 'Upper East Side, Manhattan', true, 0
from public.listings l where l.slug = 'barbershop-ues'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/dry-cleaners-uws.jpg', caption = 'Upper West Side, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'dry-cleaners-uws';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-uws.jpg', 'Upper West Side, Manhattan', true, 0
from public.listings l where l.slug = 'dry-cleaners-uws'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/wash-fold-drop-store-ues.jpg', caption = 'Upper East Side, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'wash-fold-drop-store-ues';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/wash-fold-drop-store-ues.jpg', 'Upper East Side, Manhattan', true, 0
from public.listings l where l.slug = 'wash-fold-drop-store-ues'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-washington-heights-absentee-run.jpg', caption = 'Washington Heights, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-washington-heights-absentee-run';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-washington-heights-absentee-run.jpg', 'Washington Heights, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-washington-heights-absentee-run'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/bagel-shop-cafe-bronx.jpg', caption = 'Bronx, Bronx'
  from public.listings l where i.listing_id = l.id and l.slug = 'bagel-shop-cafe-bronx';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/bagel-shop-cafe-bronx.jpg', 'Bronx, Bronx', true, 0
from public.listings l where l.slug = 'bagel-shop-cafe-bronx'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-harlem-great-location.jpg', caption = 'Harlem, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-harlem-great-location';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-harlem-great-location.jpg', 'Harlem, Manhattan', true, 0
from public.listings l where l.slug = 'laundromat-harlem-great-location'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/laundromat-astoria-large.jpg', caption = 'Astoria, Queens'
  from public.listings l where i.listing_id = l.id and l.slug = 'laundromat-astoria-large';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/laundromat-astoria-large.jpg', 'Astoria, Queens', true, 0
from public.listings l where l.slug = 'laundromat-astoria-large'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/dry-cleaners-midtown-east.jpg', caption = 'Midtown East, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'dry-cleaners-midtown-east';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/dry-cleaners-midtown-east.jpg', 'Midtown East, Manhattan', true, 0
from public.listings l where l.slug = 'dry-cleaners-midtown-east'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/greek-turkish-restaurant-tribeca.jpg', caption = 'Tribeca, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'greek-turkish-restaurant-tribeca';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/greek-turkish-restaurant-tribeca.jpg', 'Tribeca, Manhattan', true, 0
from public.listings l where l.slug = 'greek-turkish-restaurant-tribeca'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

update public.listing_images i set url = '/img/listings/cafe-pizzeria-ues-flagship.jpg', caption = 'Upper East Side, Manhattan'
  from public.listings l where i.listing_id = l.id and l.slug = 'cafe-pizzeria-ues-flagship';
insert into public.listing_images (listing_id, url, caption, is_primary, sort_order)
select l.id, '/img/listings/cafe-pizzeria-ues-flagship.jpg', 'Upper East Side, Manhattan', true, 0
from public.listings l where l.slug = 'cafe-pizzeria-ues-flagship'
  and not exists (select 1 from public.listing_images i where i.listing_id = l.id);

