// Canonical NDA text. Keep in sync with the NDA_AGREEMENT constant in
// public/js/public.js (same VERSION when they match). Source: NGU's
// "TEMPLATE - NDA - NGU Biz Real Estate.docx".

const VERSION = 'v1-2026';
const TITLE = "BUYER'S ACKNOWLEDGEMENT OF INTRODUCTION AND CONFIDENTIALITY AGREEMENT";

function intro(business) {
  return 'The undersigned Buyer, individually and on behalf of any affiliated prospective buyer, '
    + 'acknowledges being first introduced to and requests Confidential Information about the '
    + 'following business: ' + business + ', identified herein by Brokerage NGU Business Real '
    + 'Estate, Edward Lee, an agent of NGU Business Real Estate (Broker). Such Confidential '
    + 'Information shall be provided to Buyer for the sole purpose of evaluating the possible '
    + 'purchase by Buyer of all or part of the stock or assets of the Business. As used in this '
    + 'agreement (Agreement), the term Buyer applies to the undersigned and any partnership, '
    + 'corporation, individual, or other entity with which the undersigned is affiliated. Buyer '
    + 'agrees as follows:';
}

const SECTIONS = [
  { n: 1, heading: 'NON-DISCLOSURE OF INFORMATION',
    body: "Buyer acknowledges that the owner of the Business (Seller) desires to maintain the confidentiality of the information disclosed. Buyer agrees not to disclose or permit access to any Confidential Information without the prior written consent of the Seller, to anyone other than Buyer's legal counsel, accountants, lenders, or other agents or advisors to whom disclosure or access is necessary for Buyer to evaluate the Business. Disclosure of the Confidential Information shall be made to these parties only in connection with the potential acquisition of the Business, and then only if these parties understand and agree to maintain the confidentiality of such Confidential Information. Buyer shall be responsible for any breach of this Agreement by these parties, and neither Buyer nor these parties shall use or permit the use of Confidential Information in any manner whatsoever, except as may be required for Buyer to evaluate the Business or as may be required by legal process. If the Buyer does not purchase the Business, Buyer, at the close of negotiations, will destroy or return to Broker (at Seller's direction) all information provided to Buyer and will not retain any copy, reproduction, or record thereof." },
  { n: 2, heading: 'DEFINITION OF "CONFIDENTIAL INFORMATION"',
    body: 'The term "Confidential Information" shall mean all information including the fact that the Business is for sale, all financial, production, marketing and pricing information, business methods, business manuals, manufacturing procedures, correspondence, processes, data, contracts, customer lists, employee lists, and any other information whether written, oral, or otherwise made known to Buyer; (a) from any inspection, examination, or other review of the books, records, assets, liabilities, processes, or production methods of Seller; (b) from any communication with Seller or Seller\'s broker, directors, officers, employees, agents, suppliers, customers or representatives; (c) during visits to Seller\'s premises; or (d) through disclosure or discovery in any other manner.' },
  { n: 3, heading: "BUYER'S RESPONSIBILITY AND DISCLAIMER OF BROKER'S LIABILITY",
    body: "NGU Business Real Estate has received information about this Business from the Seller which may include, but is not limited to, tax returns, financial statements, equipment lists, and facility leases. Based on information provided by sellers, NGU Business Real Estate often prepare a summary description of the business which may include a cash flow projection, an adjusted income statement, or a seller discretionary cash flow statement. Buyer understands that the Broker does not audit or verify any information given to Broker or make any warranty or representation as to its accuracy or completeness, nor in any way guarantee future business performance. Buyer is solely responsible to examine and investigate the Business, its assets, liabilities, financial statements, tax returns, and any other facts which might influence Buyer's purchase decision or the price Buyer is willing to pay. Any decision by Buyer to purchase the Business shall be based solely on Buyer's own investigation and that of Buyer's legal, tax, and other advisors and not that of NGU Business Real Estate. Any costs incurred from consultations with advisors throughout the acquisition period will be the sole and exclusive responsibility of the Buyer." },
  { n: 4, heading: 'NON-CIRCUMVENTION AGREEMENT',
    body: "The Seller has entered into an agreement providing that Seller shall pay a fee to the listing broker if, during the term of that agreement or up to twelve months thereafter, the Business is transferred to a buyer introduced by the listing broker or a cooperating broker. Buyer shall conduct all inquiries into and discussions about the Business solely through Broker and shall not directly contact the Seller or the Seller's representatives. Should Buyer purchase all or part of the stock or assets of Business, acquire any interest in, execute any lease at the Business premises, or become affiliated in any capacity with Business without Broker's participation, or in any way interfere with Brokers' right to a fee, buyer shall be liable to the listing broker and the cooperating broker for such fee and any other damages including reasonable attorney's fees. Buyer also acknowledges that the Broker MUST BE NOTIFIED of ALL CONTRACTS, CLOSING DATES, TIMES AND LOCATIONS." },
  { n: 5, heading: 'FURTHER TERMS',
    body: "Neither Buyer nor Buyer's agents will contact Seller's employees, customers, landlords, or suppliers, nor linger or otherwise observe the Business, without Seller's consent. For three years, Buyer shall not directly or indirectly solicit for employment any employees of Seller. Broker may act as a dual agent representing both Buyer and Seller. Seller and Seller's successors are specifically intended to be beneficiaries of the duties and obligations of this Agreement and may prosecute any action at law or in equity necessary to enforce its terms and conditions as though a party hereto. This Agreement can only be modified in writing, signed by both Broker and Buyer. Waiver of any breach of this Agreement shall not be a waiver of any subsequent breach. This Agreement supersedes all prior understandings or agreements between the parties with respect to its subject matter. This Agreement shall be construed under and governed by the laws of the State of New York. The venue for any action instituted to enforce any terms of the Agreement shall be in the county in which the Business is located. This Agreement may be signed in counterparts and faxed and electronic signatures may be considered as originals. Buyer acknowledges receipt of a fully completed copy of this Agreement." },
];

module.exports = { VERSION, TITLE, intro, SECTIONS };
