# Concatenates the migrations + seed into supabase/all_in_one.sql, so the whole
# database can be created with a single paste into the Supabase SQL Editor.
#
# Run after changing any migration or regenerating the seed:
#   node  tools/build-catalogue.mjs      # regenerates seed.sql (and demo-data.js)
#   pwsh  tools/build-all-in-one.ps1     # then re-bundle

$ErrorActionPreference = 'Stop'
$p   = Join-Path $PSScriptRoot '..\supabase' | Resolve-Path
$out = Join-Path $p 'all_in_one.sql'

# Keep this header pure ASCII: Windows PowerShell reads .ps1 files as ANSI
# unless they carry a BOM, so non-ASCII typed here would itself be mangled.
$header = @"
-- =============================================================================
-- NGU Business Real Estate CMS - COMPLETE database setup, in one file.
--
-- Paste this whole file into the Supabase SQL Editor and hit Run. It is the
-- concatenation of, in order:
--   migrations/0001_init.sql    - schema, RLS, public RPCs
--   migrations/0002_brokers.sql - brokers + listing/lead attribution
--   seed.sql                    - 2 brokers + the 22-listing catalogue
--
-- Safe to re-run: the seed uses ON CONFLICT DO NOTHING / NOT EXISTS guards.
-- Generated by tools/build-all-in-one.ps1 - do not hand-edit.
-- =============================================================================


"@

$parts = @(
  @{ label = '0001_init.sql';    file = Join-Path $p 'migrations\0001_init.sql' },
  @{ label = '0002_brokers.sql'; file = Join-Path $p 'migrations\0002_brokers.sql' },
  @{ label = 'seed.sql';         file = Join-Path $p 'seed.sql' }
)

$sb = New-Object System.Text.StringBuilder
[void]$sb.Append($header)
foreach ($part in $parts) {
  if (-not (Test-Path $part.file)) { throw "Missing $($part.file)" }
  [void]$sb.AppendLine('-- ===========================================================================')
  [void]$sb.AppendLine("-- BEGIN $($part.label)")
  [void]$sb.AppendLine('-- ===========================================================================')
  [void]$sb.AppendLine('')
  # Read as UTF-8 explicitly. Get-Content -Raw uses the ANSI codepage in
  # Windows PowerShell 5.1, which mangles the em-dashes, accented letters and
  # curly quotes in the listing data (they end up double-encoded on write).
  [void]$sb.AppendLine([System.IO.File]::ReadAllText($part.file, [System.Text.Encoding]::UTF8))
  [void]$sb.AppendLine('')
}

# UTF8 without BOM — the Supabase SQL editor chokes on a leading BOM.
[System.IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
Write-Output "Wrote $out ($((Get-Content $out | Measure-Object -Line).Lines) lines)"
